# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  schedule:
    - cron: "*/5 * * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run the script
        run: sh script.sh
