# This is a basic workflow to help you get started with Actions

name: Scan

# Controls when the workflow will run
on:
  schedule:
    - cron: "* * * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run the script
        run: sh script.sh
        env:
          BOCA_EMAIL: ${{ secrets.BOCA_EMAIL }}
          BOCA_PASSWORD: ${{ secrets.BOCA_PASSWORD }}
